package com.salt.apps.moov.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF3D0077)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEEDCFF)
val md_theme_light_onPrimaryContainer = Color(0xFF290054)
val md_theme_light_secondary = Color(0xFF645A6F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEBDDF7)
val md_theme_light_onSecondaryContainer = Color(0xFF20182A)
val md_theme_light_tertiary = Color(0xFF80525A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9DE)
val md_theme_light_onTertiaryContainer = Color(0xFF321018)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1D1B1E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1D1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE8E0EB)
val md_theme_light_onSurfaceVariant = Color(0xFF4A454E)
val md_theme_light_outline = Color(0xFF7B757F)
val md_theme_light_inverseOnSurface = Color(0xFFF5EFF4)
val md_theme_light_inverseSurface = Color(0xFF322F33)
val md_theme_light_inversePrimary = Color(0xFFD9B9FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF7446AF)
val md_theme_light_outlineVariant = Color(0xFFCCC4CF)
val md_theme_light_scrim = Color(0xFF000000)